### ISSUE TITLE
For future labs, provide hard-coded test harnesses instead of requiring user input

### ISSUE THREAD

**Issue by adeet1** [uva-cs/pdr#29]
A hard-coded test harness may make it simpler for students to run the main method without having to pipe in input each time (e.g. ./a.out < testfile1.txt). A hard-coded test harness could show actual (what the student's code is returning) vs. expected (the output that the graders are looking for) values, making it easier for students to quickly see if their code is running properly.

#### Example
For post-lab 5, instead of having students do this execution:
`./a.out < testfile1.txt`
AVL path: can't created
AVL numNodes: 17

`head testfile1.out.txt`
AVL path: problems can't kind created
AVL numNodes: 18

They can do this execution:
`./a.out`
AVL path (actual): can't created
AVL path (expected): problems can't kind created
AVL numNodes (actual): 17
AVL numNodes (expected): 18

#### The code for such a test harness would be like:
```
AVLTree t1;
t1.insert("We");
t1.insert("can't");
t1.insert("solve");
t1.insert("problems");
t1.insert("by");
t1.insert("using");
t1.insert("the");
t1.insert("same");
t1.insert("kind");
t1.insert("of");
t1.insert("thinking");
t1.insert("we");
t1.insert("used");
t1.insert("when");
t1.insert("we");
t1.insert("created"); 
t1.insert("them");
t1.insert("-Albert");
t1.insert("Einstein");
cout << "Actual  : " << t1.pathTo("created") << endl;
cout << "Expected: problems can't kind created" << endl;
cout << "Actual  : " << t1.numNodes() << endl;
cout << "Expected: 18" << endl;
```

**Comment by adeet1** [comment]
An example of a hard-coded test harness would be:
```
AVLTree t1;
t1.insert("We");
t1.insert("can't");
t1.insert("solve");
t1.insert("problems");
t1.insert("by");
t1.insert("using");
t1.insert("the");
t1.insert("same");
t1.insert("kind");
t1.insert("of");
t1.insert("thinking");
t1.insert("we");
t1.insert("used");
t1.insert("when");
t1.insert("we");
t1.insert("created"); 
t1.insert("them");
t1.insert("-Albert");
t1.insert("Einstein");
cout << "Actual  : " << t1.pathTo("created") << endl;
cout << "Expected: problems can't kind created" << endl;
cout << "Actual  : " << t1.numNodes() << endl;
cout << "Expected: 18" << endl;
```

**Comment by 50Wliu** [comment]
This would be nice, but on the other hand, the current system is a good refresher on how to programmatically pass in input to a program.

**Comment by adeet1** [comment]
Makes sense. Actually, even if the test harness isn't hard-coded, it could still print the expected value. This could be done using if statements:

```
int main() {
  AVLTree avl;
  while (cin.good()) {
    string instr, word;
    cin >> instr;
    cin >> word;
    if (instr == "I") {
      avl.insert(word);
    } else if (instr == "R") {
      avl.remove(word);
    } else if (instr == "L") {
      cout << "AVL path: " << avl.pathTo(word) << endl;
      /* pseudocode:
       if (input file == testfile1.txt)
           cout << "problems can't kind created" << endl;

       --- and likewise for the other two test files ---
       */
    }
  }
  cout << "AVL numNodes: " << avl.numNodes() << endl;
}
```
